##
## Makefile for List in /home/mougen_v/rendus/PSU_2013_zappy/libs
##
## Made by Valentin
## Login   <mougen_v@epitech.net>
##
## Started on  Sun Jul 13 18:08:14 2014 Valentin
## Last update Sun Jul 13 18:08:15 2014 Valentin
##

LIST		=	list

all		:
			@(make -C $(LIST))

clean		:
			@(cd $(LIST) && make clean)

fclean		:
			@(cd $(LIST) && make fclean)

re		:
			@(cd $(LIST) && make re)

.PHONY		:	all clean fclean re
